version: '3'
services:
    web:
        container_name: nginx-app
        image: nginx:latest
        restart: always
        ports:
        - "80:80"
        volumes:
        - ./app:/var/www/html/app
        - ./server/volumes/nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
        container_name: redis-app
        image: redis
        restart: always
        ports:
        - "6379:6379"
        networks:
          default:
            ipv4_address: 172.10.0.6
    mysql:
        container_name: mysql-app
        image: mysql:5.7
        ports:
        - "33061:3306"
        - "3306:3306"
        volumes:
        - ./server/volumes/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
          default:
            ipv4_address: 172.10.0.5
    php:
        container_name: php-app
        build: server/builds/php
        image: php:fpm
        restart: always
        volumes:
        - ./app:/var/www/html/app
        - ./server/bashes/laravel.sh:/var/www/html/laravel.sh
    mongo:
        container_name: mongo-resta
        image: mongo
        ports:
          - "27017:27017"
        volumes:
          - ./server/volumes/mongo:/data/db
        networks:
          default:
            ipv4_address: 172.10.0.7
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

