version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        volumes:
            - ./server/volumes/elasticsearch/data:/usr/share/elasticsearch/data
        container_name: es01
        environment:
            - node.name=es01
            - cluster.initial_master_nodes=es01
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            default:
                ipv4_address: 172.10.0.10
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

