version: '3'
services:
    php:
        container_name: php-app
        build: server/builds/php
        image: php:fpm
        restart: always
        volumes:
        - ./app:/var/www/html/app
        - ./server/bashes/laravel.sh:/var/www/html/laravel.sh
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

