version: '3'
services:
    web:
        container_name: nginx-app
        image: nginx:latest
        restart: always
        ports:
        - "80:80"
        volumes:
        - ./app:/var/www/html/app
        - ./server/volumes/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                ipv4_address: 172.10.0.13
    php:
        container_name: php-app
        build: server/builds/php
        image: php:fpm
        restart: always
        volumes:
        - ./app:/var/www/html/app
        - ./server/bashes/laravel.sh:/var/www/html/laravel.sh
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

