version: '3'
services:
    redis:
        container_name: redis-app
        image: redis
        restart: always
        ports:
        - "6379:6379"
        networks:
          default:
            ipv4_address: 172.10.0.6
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

